openapi: 3.1.0
info:
    version: 1.0.0
    title: Water App
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: This is a documentation for Contacts app
tags:
    - name: Water info
      description: Water operations
    - name: Authentication
      description: Authentication operations
servers:
    - url: https://aqua-server-83k1.onrender.com
    - url: http://localhost:8080
paths:
    /auth/signup:
        post:
            $ref: ../swagger/paths/auth/signup.yaml
    /auth/signin:
        post:
            $ref: ../swagger/paths/auth/signin.yaml
    /auth/logout:
        post:
            $ref: ../swagger/paths/auth/logout.yaml

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
